### ISSUE TITLE
Error in wire library when compiling a sketch

### ISSUE THREAD

**Issue by upassern** [CONTROLLINO-PLC/CONTROLLINO_Library#3]
After upgrading to new BSP Version 2.0.0, compiling a sketch isn't possible anymore. 

Error-Log: "Library can't use both 'src' and 'utility' folders. Double check C:\Users\Ulli\Documents\ArduinoData\packages\CONTROLLINO_Boards\hardware\avr\2.0.0\libraries\Wire"

I substituted this Wire Library with the Wire-Library in "c:\Program Files\WindowsApps\ArduinoLLC.ArduinoIDE_1.8.6.0_x64__mdqgnx93n4wtt\hardware\" and the sketch was successfully compiled. 

Because the compare of the both Wire Libraries shows some minor differences, I don't want to upload the sketch to the Controllino. 

Please correct the problem in the BSP Wire Library.

**Comment by CONTROLLINO-Support** [comment]
Thank you for the bugreport!

Fixed in BSP 2.0.1. 

Please update the BSP in your Arduino IDE.
If you will have some compilation error like "controllino-mega is not a known board", please go to a folder c:\Users\UserName\AppData\Local\Arduino15\packages\CONTROLLINO_Boards\hardware\avr\ and delete obsolete folder 2.0.0.
